// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ef_gardening;

namespace ef_gardening.Migrations
{
    [DbContext(typeof(GardeningContext))]
    partial class GardeningContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ef_gardening.Models.Family", b =>
                {
                    b.Property<int>("FamilyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FamilyID");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("ef_gardening.Models.Plant", b =>
                {
                    b.Property<int>("PlantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommonName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FamilyID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<int?>("RegionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScientificName")
                        .HasColumnType("TEXT");

                    b.HasKey("PlantID");

                    b.HasIndex("FamilyID");

                    b.HasIndex("RegionID");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("ef_gardening.Models.Region", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("ef_gardening.Models.Plant", b =>
                {
                    b.HasOne("ef_gardening.Models.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyID");

                    b.HasOne("ef_gardening.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID");
                });
#pragma warning restore 612, 618
        }
    }
}
